#write a docker compose configuration file for node.js
#docker-compose.yml
version: '3'
services:
  api:
    container_name: auth-api
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://admin:password@mongodb:27017
    command: "npm start"
    networks:
      - default

  mongodb:
    container_name: auth-database
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=authenication_service
    networks:
      - default

networks:
  default:
    driver: bridge
